# Generated by Django 3.2 on 2021-05-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_link', models.URLField(blank=True, max_length=500)),
                ('faceboo_link', models.URLField(blank=True, max_length=500)),
                ('instagram_link', models.URLField(blank=True, max_length=500)),
                ('youtube_link', models.URLField(blank=True, max_length=500)),
                ('address_line_1', models.TextField(blank=True, max_length=50)),
                ('address_line_2', models.TextField(blank=True, max_length=50)),
                ('city', models.TextField(blank=True, max_length=50)),
                ('state', models.TextField(blank=True, max_length=50)),
                ('country', models.TextField(blank=True, max_length=50)),
                ('phone', models.TextField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Contact Us', max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='photos/contact')),
            ],
        ),
    ]
