# Generated by Django 3.2 on 2021-05-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IAboutUSSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_image', models.ImageField(upload_to='photos/about')),
                ('top_title', models.TextField(blank=True, max_length=100)),
                ('top_sub_title', models.TextField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='IIAboutTextImageAlterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/about')),
                ('push_image_to_left', models.BooleanField(default=True)),
                ('title', models.TextField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, max_length=600)),
                ('button_name', models.CharField(default='More Details', max_length=100)),
                ('hyperlink', models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='IIICompanyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, default='Company Progress', max_length=100)),
                ('percentage_progress', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='IVWorkingSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(blank=True, max_length=150)),
                ('image', models.ImageField(blank=True, upload_to='photos/about')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='VISubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(blank=True, default='Subscribe to our newsletter to get our news and deals delivered to your inbox!', max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='photos/about')),
                ('button_name', models.CharField(blank=True, max_length=50)),
                ('hyperlink', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='VTeamBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(blank=True, default='Team Members', max_length=100)),
                ('name', models.CharField(blank=True, default='Team Memebers name', max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=150)),
                ('twitter_link', models.URLField(blank=True, max_length=500)),
                ('facebook_link', models.URLField(blank=True, max_length=500)),
                ('instagram_link', models.URLField(blank=True, max_length=500)),
            ],
        ),
    ]
