# Generated by Django 3.2 on 2021-05-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vteambox',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/about'),
        ),
    ]
