# Generated by Django 3.2 on 2021-05-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IIAdvertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/chatbot')),
                ('title', models.TextField(blank=True, max_length=150)),
                ('point1', models.TextField(blank=True, max_length=150)),
                ('point2', models.TextField(blank=True, max_length=150)),
                ('point3', models.TextField(blank=True, max_length=150)),
                ('point4', models.TextField(blank=True, max_length=150)),
                ('benefit_for', models.TextField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='IIICustomerUsingOurChatBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=200)),
                ('name_company', models.TextField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='photos/chatbot')),
            ],
        ),
        migrations.CreateModel(
            name='ISlidingScreenShotImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/chatbot')),
                ('heading', models.TextField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='IVSecondAdvertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.TextField(blank=True, max_length=150)),
                ('title_2', models.TextField(blank=True, max_length=150)),
                ('description_1', models.TextField(blank=True, max_length=300)),
                ('description_2', models.TextField(blank=True, max_length=150)),
                ('image_1', models.ImageField(upload_to='photos/chatbot')),
                ('image_title_1', models.TextField(blank=True, max_length=150)),
                ('image_description_1', models.TextField(blank=True, max_length=150)),
                ('slogan_1', models.TextField(blank=True, max_length=150)),
                ('image_2', models.ImageField(upload_to='photos/chatbot')),
                ('image_title_2', models.TextField(blank=True, max_length=150)),
                ('image_description_2', models.TextField(blank=True, max_length=150)),
                ('slogan_2', models.TextField(blank=True, max_length=150)),
            ],
        ),
    ]
