# Generated by Django 3.2 on 2021-05-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='islidingimage',
            name='button_name',
            field=models.TextField(blank=True, default='See Our Project', max_length=200),
        ),
    ]
