# Generated by Django 3.2 on 2021-05-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_top_image',
            field=models.ImageField(blank=True, upload_to='photos/blog'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/blog'),
        ),
    ]
