# Generated by Django 3.2 on 2021-05-29 06:01

import ckeditor.fields
from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtificialIntellience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('video', embed_video.fields.EmbedVideoField(blank=True, max_length=500, null=True)),
                ('description_after_video', models.TextField(blank=True, max_length=500)),
                ('heading', models.CharField(blank=True, max_length=100)),
                ('more_details', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/ai')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('button_name', models.CharField(blank=True, max_length=50)),
                ('hyperlink', models.URLField(blank=True, max_length=500)),
            ],
        ),
    ]
