# Generated by Django 3.2 on 2021-05-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceslist',
            name='button_name',
            field=models.CharField(default='Learn More', max_length=50),
        ),
    ]
