# Generated by Django 3.2 on 2021-05-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ICareerSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_title', models.CharField(blank=True, default='Work With Us', max_length=100)),
                ('short_note', models.CharField(blank=True, default='A Note On', max_length=100)),
                ('short_note_animated_text', models.CharField(blank=True, default='Our Culture', max_length=100)),
                ('description_of_short_note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='IICurrentOpeningPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, default='Internship', max_length=100)),
                ('location', models.TextField(blank=True, default='Chakupat, Lalitpur, Nepal', max_length=300)),
                ('title', models.TextField(blank=True, default='Software Engineer', max_length=200)),
                ('payment', models.TextField(blank=True, default='Negotiable', max_length=300)),
                ('Deadline', models.TextField(blank=True, default='01/01/20..', max_length=200)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='IIIWoringWithUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, default='Benefits of Working With Us', max_length=100)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('title_id', models.CharField(max_length=50)),
            ],
        ),
    ]
