# Generated by Django 3.2 on 2021-05-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Career', '0003_ivworkingwithuscontent_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='icareersection',
            name='top_description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='icareersection',
            name='top_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/career'),
        ),
        migrations.AddField(
            model_name='ivworkingwithuscontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/career'),
        ),
    ]
