# Generated by Django 3.2 on 2021-05-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Career', '0004_auto_20210529_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(max_length=100)),
                ('phone', models.TextField(max_length=15)),
                ('resume', models.FileField(upload_to='files/resume')),
                ('strength', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
