# Generated by Django 3.2 on 2021-05-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Career', '0005_resumesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumesection',
            name='position',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resumesection',
            name='title',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
