# Generated by Django 3.2 on 2021-05-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Career', '0006_auto_20210529_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumesection',
            name='resume',
            field=models.FileField(upload_to='files'),
        ),
    ]
