# Generated by Django 3.2 on 2021-05-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Career', '0007_alter_resumesection_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumesection',
            name='resume',
            field=models.FileField(blank=True, upload_to='files'),
        ),
    ]
