# Generated by Django 3.2 on 2021-05-31 08:17

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='I_1_RoboticsPageTopContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=100)),
                ('youtube_link', embed_video.fields.EmbedVideoField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='I_2_RoboticsPageTypeOfRobot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_robot', models.TextField(max_length=100, unique=True)),
                ('slug', models.TextField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='photos/robo')),
                ('push_imge_to_left', models.BooleanField(default=True)),
                ('title', models.TextField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='I_3_RoboticsPageDeployRobotsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(blank=True, max_length=100)),
                ('title', models.TextField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='photos/robo')),
                ('category_title', models.TextField(blank=True, max_length=100)),
                ('category_description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='I_4_RoboticsPageExpertiseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(blank=True, max_length=100)),
                ('title', models.TextField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='photos/robo')),
                ('category_title', models.TextField(blank=True, max_length=100)),
                ('category_description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Z_4_TypeOfRobotPageHowWeDoIT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(blank=True, max_length=100)),
                ('title', models.TextField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='photos/robo')),
                ('category_title', models.TextField(blank=True, max_length=100)),
                ('category_description', models.TextField(blank=True, max_length=500)),
                ('robot_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Robotics.i_2_roboticspagetypeofrobot')),
            ],
        ),
        migrations.CreateModel(
            name='Z_3_TypeOfRobotEveryThingRobotics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(blank=True, max_length=100)),
                ('title', models.TextField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='photos/robo')),
                ('push_image_to_left', models.BooleanField(default=True)),
                ('category_title', models.TextField(blank=True, max_length=100)),
                ('category_description', models.TextField(blank=True, max_length=500)),
                ('robot_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Robotics.i_2_roboticspagetypeofrobot')),
            ],
        ),
        migrations.CreateModel(
            name='Z_2_TypeOfRobotPageDeployRobot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(blank=True, max_length=100)),
                ('title', models.TextField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='photos/robo')),
                ('category_title', models.TextField(blank=True, max_length=100)),
                ('category_description', models.TextField(blank=True, max_length=500)),
                ('robot_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Robotics.i_2_roboticspagetypeofrobot')),
            ],
        ),
        migrations.CreateModel(
            name='Z_1_TypeOfRobotPageTopContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=100)),
                ('youtube_link', embed_video.fields.EmbedVideoField(blank=True, max_length=500, null=True)),
                ('robot_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Robotics.i_2_roboticspagetypeofrobot')),
            ],
        ),
    ]
