# Generated by Django 3.2 on 2021-05-31 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Robotics', '0002_auto_20210531_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='z_1_typeofrobotpagetopcontent',
            name='robot_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Robotics.i_2_roboticspagetypeofrobot'),
        ),
    ]
