# Generated by Django 3.2 on 2021-05-31 10:48

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Robotics', '0003_alter_z_1_typeofrobotpagetopcontent_robot_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Z_1_TypeOfRobotPageTopContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('youtube_link', embed_video.fields.EmbedVideoField(blank=True, max_length=500, null=True)),
                ('robot_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Robotics.i_2_roboticspagetypeofrobot')),
            ],
        ),
        migrations.DeleteModel(
            name='Z_1_TypeOfRobotPageTopContent',
        ),
    ]
